name: Deploy Resource Group

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      rg_name:
        description: 'Resource Group Name'
        required: true
      rg_location:
        description: 'Azure Region (optional, defaults to East US)'
        required: false
        default: ''

env:
  AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
  AZURE_STORAGE_CONTAINER: "tf-infra"
  AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  # Compose a unique tfstate file per resource group
  TFSTATE_KEY: ${{ github.event.inputs.rg_name }}.tfstate

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/resource_group   # Adjust if your TF code is elsewhere

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'

      # Minimal backend.tf file so tf init can set backend args via CLI
      - name: Create minimal backend.tf
        run: |
          cat > backend.tf <<EOF
          terraform {
            backend "azurerm" {}
          }
          EOF

      # Pass tfstate filename via backend-config CLI using env variable
      - name: Terraform Init
        run: |
          terraform init -input=false \
            -backend-config="storage_account_name=${{ env.AZURE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ env.AZURE_STORAGE_CONTAINER }}" \
            -backend-config="key=${{ env.TFSTATE_KEY }}" \
            -backend-config="access_key=${{ env.AZURE_STORAGE_KEY }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Set Location with Default
        id: set_location
        run: |
          if [ -z "${{ github.event.inputs.rg_location }}" ]; then
            echo "effective_location=East US" >> $GITHUB_OUTPUT
          else
            echo "effective_location=${{ github.event.inputs.rg_location }}" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Plan (Apply)
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terraform plan -input=false \
            -var="rg_name=${{ github.event.inputs.rg_name }}" \
            -var="rg_location=${{ steps.set_location.outputs.effective_location }}" \
            -var="subscription_id=${{ env.AZURE_SUBSCRIPTION_ID }}" \
            -out=tfplan

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -input=false -auto-approve tfplan

      - name: Terraform Plan Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          terraform plan -destroy -input=false \
            -var="rg_name=${{ github.event.inputs.rg_name }}" \
            -var="rg_location=${{ steps.set_location.outputs.effective_location }}" \
            -var="subscription_id=${{ env.AZURE_SUBSCRIPTION_ID }}" \
            -out=tfdestroy

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform apply -input=false -auto-approve tfdestroy
